[package]
name = "aurora"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
